# Deprecated workflow: build & deploy (superseded by CI/CD Pipeline in dotnet.yml)
# Keeping for manual fallback only. It no longer runs automatically on push.
# To use manually, trigger via the GitHub UI (workflow_dispatch).

name: (Deprecated) Manual Deploy ASP.Net Core app to Azure Web App - Fiszki

on:
  workflow_dispatch:

jobs:
  build-and-deploy-manual:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Fiszki.sln

      - name: Build with dotnet
        run: dotnet build Fiszki.sln --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish Fiszki.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Fiszki'
          slot-name: 'Production'
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_93FA90C48A7B43BE9A3E282FD84CA1DA }}